services:
  neo4j:
    image: neo4j:5.13
    container_name: dg-rag-neo4j           # ← ここ！
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - dg_rag_neo4j_data:/data            # ← ここ！
volumes:
  dg_rag_neo4j_data:                       # ← ここ！
